version: "3.7"

services:
  web:
    build: .
    command: sh -c "composer install && npm install && npm run dev && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port 80"
    restart: unless-stopped
    volumes:
      - ./:/app:delegated
    ports:
      - "9000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:GMzACCCJOpnY+Ih6+KtWAkIs3Io1Inmn9DZ/d28w7XI=
      - APP_DEBUG=true
      - APP_URL=http://localhost:9000
      - LOG_CHANNEL=stack

      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=admin
      - DB_PASSWORD=admin

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=cookie
      - SESSION_LIFETIME=120

      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME="$${APP_NAME}"

      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=

      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1

      - MIX_PUSHER_APP_KEY="$${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="$${PUSHER_APP_CLUSTER}"
    depends_on:
      - database

  database:
    image: mysql:8.0.18
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "8992:3306"
